;-------------------------------------------------------------------------
;   KEYS MACRO FILE FOR ASSEMBLER LABORATORY (C) KURT INGE GR0NBECH
;-------------------------------------------------------------------------
;   In this file you set up the keys for various functions in ALab,
;   and you can create macros for keys (have multiple functions on
;   one key). Keycode names and function names are NOT case-sensitive.
;
;   NB!
;       þ You have to start ALab with the '/K' switch after you have
;         changed something in this file, in order to have the changes
;         take effect.
;       þ EVERY function have to be defined here (after each other),
;         except 'block comment/uncomment',
;         even if they don't have a shortcut key. This because it
;         spares the author for many valuable minutes of extra programming
;         :)
;       þ A semicolon in first column starts a comment line
;       þ The keycode name does not have to come at column 33, it only
;         has to be a blank between the function name and keycode name.
;
;-------------------------------------------------------------------------
;                            Valid keys
;อออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออ
;
;ÝkbXXXX Alt-Letter Key CodesÞ
;
; Constant    บ Constant
;อออออออออออออฮอออออออออออ
; kbAltA      บ kbAltN
; kbAltB      บ kbAltO
; kbAltC      บ kbAltP
; kbAltD      บ kbAltQ
; kbAltE      บ kbAltR
; kbAltF      บ kbAltS
; kbAltG      บ kbAltT
; kbAltH      บ kbAltU
; kbAltI      บ kbAltV
; kbAltJ      บ kbAltW
; kbAltK      บ kbAltX
; kbAltL      บ kbAltY
; kbAltM      บ kbAltZ
;
;
;ÝkbXXXX Special Key CodesÞ
;
; Constant    บ Constant
;อออออออออออออฮอออออออออออ
; kbAltEqual  บkbEnd
; kbAltMinus  บkbEnter
; kbAltSpace  บkbEsc
; kbBack      บkbGrayMinus
; kbCtrlBack  บkbHome
; kbCtrlDel   บkbIns
; kbCtrlEnd   บkbLeft
; kbCtrlEnter บkbNoKey
; kbCtrlHome  บkbPgDn
; kbCtrlIns   บkbPgUp
; kbCtrlLeft  บkbGrayPlus
; kbCtrlPgDn  บkbRight
; kbCtrlPgUp  บkbShiftDel
; kbCtrlPrtSc บkbShiftIns
; kbCtrlRight บkbShiftTab
; kbDel       บkbTab
; kbDown      บkbUp
; kbAltBack   บ
;
;ÝkbXXXX Alt-Number Key CodesÞ
;
; Constant    บ Constant
;อออออออออออออฮอออออออออออ
; kbAlt1      บ kbAlt6
; kbAlt2      บ kbAlt7
; kbAlt3      บ kbAlt8
; kbAlt4      บ kbAlt9
; kbAlt5      บ kbAlt0
;
;ÝkbXXXX Function Key CodesÞ
;
; Constant    บ Constant
;อออออออออออออฮอออออออออออ
; kbF1        บ kbF6
; kbF2        บ kbF7
; kbF3        บ kbF8
; kbF4        บ kbF9
; kbF5        บ kbF10
;
;ÝkbXXXX Shift-Function Key CodesÞ
;
; Constant    บ Constant
;อออออออออออออฮอออออออออออ
; kbShiftF1   บ kbShiftF6
; kbShiftF2   บ kbShiftF7
; kbShiftF3   บ kbShiftF8
; kbShiftF4   บ kbShiftF9
; kbShiftF5   บ kbShiftF10
;
;ÝkbXXXX Ctrl-Function Key CodesÞ
;
; Constant    บ Constant
;อออออออออออออฮอออออออออออ
; kbCtrlF1    บ kbCtrlF6
; kbCtrlF2    บ kbCtrlF7
; kbCtrlF3    บ kbCtrlF8
; kbCtrlF4    บ kbCtrlF9
; kbCtrlF5    บ kbCtrlF10
;
;ÝkbXXXX Alt-Function Key CodesÞ
;
; Constant    บ Constant
;อออออออออออออฮอออออออออออ
; kbAltF1     บ kbAltF6
; kbAltF2     บ kbAltF7
; kbAltF3     บ kbAltF8
; kbAltF4     บ kbAltF9
; kbAltF5     บ kbAltF10
;
;อออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออ

; File menu
FileOpen                        kbF3
FileNew                         kbShiftF8
FileSave                        kbF2
FileSaveas
FileChangeDir
FilePrint
FileGetinfo
FileDoscommand                  kbF7
FileDosShell
FileExit                        kbAltX

; Edit menu
EditUndo                        kbAltBack
EditCut                         kbShiftDel
EditCopy                        kbCtrlIns
EditPaste                       kbShiftIns
EditShowclipboard               kbCtrlF6
EditClear                       kbCtrlDel
EditRepeatKey
EditExpandTabs
EditCompressSpaces

; Search menu
SearchFind
SearchReplace
SearchAgain
SearchGotoLine
;-----------------------------------------------------------------------
; NB! Do not add keys for the Mark command. They must be [Ctrl+Q ....].
;-----------------------------------------------------------------------

; Run menu
RunRun                          kbCtrlF9
RunRunDebug
RunParameters

; Assemble menu
AssembleAssemble                kbAltF9
AssembleMake
AssembleLink                    kbF9
AssembleBuild
AssembleExetoCom                kbF8

; Tools menu
ToolsRunDebugger                kbCtrlF10
ToolsRunProfiler
ToolsAsciiTable
ToolsCalculator
ToolsProcWorkSheet              kbCtrlF1
ToolsMacroWorkSheet             kbCtrlF2
ToolsVarWorkSheet               kbCtrlF3
ToolsHeuristicScan              kbCtrlF4

; Project menu
ProjectOpen
ProjectSave
ProjectClose
ProjectAdditem
ProjectDeleteitem
ProjectLocalOptions

; Options menu
OptionsAssembler
OptionsLinker
OptionsPrograms
OptionsDirectories
OptionsDebugging
OptionsHeuristicScan
OptionsPreferences
OptionsEditor                   kbShiftF7
OptionsMouse
OptionsColors
OptionsSaveConfig
OptionsReadConfig
OptionsSaveDesktop
OptionsRetrieveDesktop

; Window menu
WindowTile
WindowCascade
WindowCloseAll
WindowSizeMove                  kbCtrlF5
WindowZoom                      kbF5
WindowNext                      kbF6
WindowPrevious                  kbShiftF6
WindowClose                     kbAltF3
WindowDosScreen                 kbAltF5
WindowProject
WindowList                      kbAltF1

; Help menu
HelpContents
HelpIndex
HelpTopicSearch                 kbShiftF1
HelpOpcodes                     kbShiftF2
HelpExtendedASCII               kbShiftF3
HelpKeyCodes                    kbShiftF4
HelpScanCodes                   kbShiftF5

;อออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออ
; Here comes the key macros (multiple functions on one key)
;
; A little disappointment here I guess: It's a matter of just stuffing
; several keys in the keyboard buffer, so you first name one key and
; then one or several other keys which are to be stuffed in the
; keyboard buffer when you press the first key.
; I have not had the time to make the keyboard macros better.
; I have also almost never used macros in other editors, so you can
; say I actually don't know very much about them.
;
; þ The keycode name must come in column 2, and then you can name
;   other keycode names one under another in column >= 3 under the
;   first keycode name.
; þ Max number of key macros is 20
; þ Max number of keycode names under each macro is 10
;
; Example:
; |1234567890---------------------------------------|
; |
; | kbAltQ
; |   kbF2
; |   kbF3
; |
; When you press Alt+Q here, the keys F2 and F3 are stuffed in the
; keyboard buffer so with the original setup you will first save the
; current file and then open another.
;อออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออ

 kbAltQ
   kbF2
   kbF3

